smileidentity/ios

SmileID.podspec
This PR points the podspec to the latest release tag
=> Update Podspec Source

CHANGELOG.md, Example/SmileID/AppDelegate.swift, SmileID.podspec, Sources/SmileID/Classes/Networking/Models/EnhancedKyc.swift, Sources/SmileID/Classes/Networking/Models/PartnerParams.swift, Sources/SmileID/Classes/SmileID.swift
- Set default value for config param on `initilize` method
- Expose initializers for `PartnerParams` and `EnhancedKycAsycResponse` models
=> Expose request and response initializers

CHANGELOG.md, README.md, SmileID.podspec, Sources/SmileID/Classes/Networking/Models/Authentication.swift, Sources/SmileID/Classes/SelfieCapture/ViewModel/SelfieCaptureViewModel.swift, Sources/SmileID/Classes/SmileID.swift
- Expose `AuthenticationRequest` and `AuthenticationResponse` initializers and properties
- Bump version to `10.0.0-beta04`
=> Expose AuthenticationRequest and AuthenticationResponse initializers

CHANGELOG.md, README.md, SmileID.podspec, Sources/SmileID/Classes/Networking/Models/EnhancedKyc.swift, Sources/SmileID/Classes/SmileID.swift, Tests/Networking/EnhancedKycTest.swift
Story: N/A
Expose the `sourceSdk` and `sourceSdkVersion` to allow them to be overridden on Flutter side
=> Expose SDK Metadata

CHANGELOG.md, SmileID.podspec, Sources/SmileID/Classes/Networking/Models/Authentication.swift, Sources/SmileID/Classes/SmileID.swift
- Declare jobType property of AuthenticationRequest as an optional
=> Declare jobType property of AuthenticationRequest as an optional

CHANGELOG.md, SmileID.podspec, Sources/SmileID/Classes/Networking/Models/PartnerParams.swift, Sources/SmileID/Classes/SmileID.swift
Declare `jobType` property of `PartnerParams` as optional
=> Declare `jobType` property of `PartnerParams` as optional

CHANGELOG.md, Example/SmileID/HomeViewModel.swift, SmileID.podspec, Sources/SmileID/Classes/DocumentVerification/Model/DocumentCaptureModel.swift, Sources/SmileID/Classes/DocumentVerification/View/DocumentCaptureInstructionView.swift, Sources/SmileID/Classes/DocumentVerification/View/DocumentCaptureView.swift, Sources/SmileID/Classes/Navigation/NavigationBar.swift, Sources/SmileID/Classes/Navigation/NavigationDestination.swift, Sources/SmileID/Classes/Navigation/ViewFactory.swift, Sources/SmileID/Classes/SmileID.swift, Sources/SmileID/Resources/Localization/en.lproj/Localizable.strings
This fixes the delegate not getting results delivered to it
=> Fix delegate

CHANGELOG.md, Example/SmileID/HomeView.swift, SmileID.podspec, Sources/SmileID/Classes/DocumentVerification/View/OrchestratedDocumentVerificationScreen.swift, Sources/SmileID/Classes/Networking/Models/EnhancedKyc.swift, Sources/SmileID/Classes/Networking/Models/PrepUpload.swift, Sources/SmileID/Classes/SelfieCapture/View/SelfieCaptureView.swift, Sources/SmileID/Classes/SelfieCapture/View/SmartSelfieInstructionsView.swift, Sources/SmileID/Classes/SmileID.swift
Bump podspec version and update changelog
=> Prepare for beta10 release

CHANGELOG.md, Example/SmileID.xcodeproj/project.pbxproj, Example/SmileID/HomeView.swift, Example/SmileID/HomeViewModel.swift, Sources/SmileID/Classes/BiometricKYC/BiometricKycResultDelegate.swift, Sources/SmileID/Classes/Networking/Models/JobStatus.swift, Sources/SmileID/Classes/Networking/Models/JobType.swift, Sources/SmileID/Classes/Networking/Models/UploadRequest.swift, Sources/SmileID/Classes/Networking/Models/ValidDocuments.swift, Sources/SmileID/Classes/Networking/SmileIDService.swift, Sources/SmileID/Classes/SelfieCapture/SmartSelfieResultDelegate.swift, Sources/SmileID/Classes/SmileID.swift, Tests/Mocks/NetworkingMocks.swift
Story: https://app.shortcut.com/smileid/story/8953
Sets up scaffolding for Biometric KYC: adds the job type, job result, public interface, delegate, and updates the IdInfo model
=> Set up Biometric KYC scaffolding

Sources/SmileID/Classes/BiometricKYC/OrchestratedBiometricKycScreen.swift, Sources/SmileID/Classes/BiometricKYC/OrchestratedBiometricKycViewModel.swift, Sources/SmileID/Classes/DocumentVerification/Model/OrchestratedDocumentVerificationViewModel.swift, Sources/SmileID/Classes/DocumentVerification/View/OrchestratedDocumentVerificationScreen.swift, Sources/SmileID/Classes/Networking/Models/PartnerParams.swift, Sources/SmileID/Classes/SelfieCapture/ViewModel/SelfieCaptureViewModel.swift, Sources/SmileID/Classes/SmileID.swift, Sources/SmileID/Classes/Views/JobSubmittable.swift
Rename partnerParams to extraPartnerParams
=> Rename partnerParams to extraPartnerParams

CHANGELOG.md, Example/Podfile.lock, SmileID.podspec, Sources/SmileID/Classes/SmileID.swift
Bumps version to 10.0.0-beta12
=> Prepare for 10.0.0-beta12

CHANGELOG.md, Sources/SmileID/Classes/DocumentVerification/Model/DocumentCaptureViewModel.swift, Sources/SmileID/Classes/Helpers/ImageUtils.swift, Sources/SmileID/Classes/Views/ImageCaptureConfirmationDialog.swift
Maintains the detected aspect ratio in the document capture preview
=> Respect aspect ratio in document capture preview

Sources/SmileID/Classes/Helpers/LocalStorage.swift, Sources/SmileID/Classes/SelfieCapture/ViewModel/SelfieCaptureViewModel.swift
Fix for missing info.json on SmartSelfie Enroll and Auth
Run any SmartSelfie Enroll and Auth results should show fine on the portal
=> fix: missing info.json

CHANGELOG.md, Example/Podfile.lock, SmileID.podspec, Sources/SmileID/Classes/SmileID.swift
Release v10.0.1 with fixes on the missing info.json issue on Smartselfie Enrollment and Smartselfie Authentication
=> feat: release 10.0.1

.github/workflows/release.yml
Trigger Release on Flutter and React Native
=> Trigger Release on Flutter and React Native

CHANGELOG.md, Example/Podfile.lock, SmileID.podspec, Sources/SmileID/Classes/SelfieCapture/View/FaceOverlayView.swift, Sources/SmileID/Classes/SelfieCapture/View/SelfieCaptureView.swift, Sources/SmileID/Classes/SelfieCapture/ViewModel/SelfieCaptureViewModel.swift, Sources/SmileID/Classes/SmileID.swift
Story: https://app.shortcut.com/smileid/story/11225
Fixes the white cutout for faces
Similar to https://github.com/smileidentity/ios/pull/109, test by taking screenshot and ensuring there is no black overlay on the cutout 
Perform a selfie capture
=> Fix white face cutout

CHANGELOG.md, Example/Podfile.lock, SmileID.podspec, Sources/SmileID/Classes/BiometricKYC/OrchestratedBiometricKycScreen.swift, Sources/SmileID/Classes/DocumentVerification/Model/OrchestratedDocumentVerificationViewModel.swift, Sources/SmileID/Classes/DocumentVerification/View/DocumentCaptureScreen.swift, Sources/SmileID/Classes/DocumentVerification/View/OrchestratedDocumentVerificationScreen.swift, Sources/SmileID/Classes/SelfieCapture/View/SelfieCaptureInstructionsScreen.swift, Sources/SmileID/Classes/SelfieCapture/ViewModel/SelfieCaptureViewModel.swift, Sources/SmileID/Classes/SmileID.swift
=> Fixed iOS Instructions Screen Bug

Example/SmileID/HomeViewModel.swift, Example/SmileID/SmileEnvironmentToggleButton.swift
Defaults the Sample app to Production instead of Sandbox
Ensure the app starts in Production. Run a job and ensure it shows up in the correct environment
=> Default Sample App to Production

Example/SmileID/SmileConfigEntryView.swift, Example/SmileID/WelcomeScreen.swift
=> Fixed PartnerID and added Scan QR

Sources/SmileID/Classes/BiometricKYC/OrchestratedBiometricKycViewModel.swift, Sources/SmileID/Classes/DocumentVerification/Model/OrchestratedDocumentVerificationViewModel.swift, Sources/SmileID/Classes/Helpers/LocalStorage.swift, Sources/SmileID/Classes/SelfieCapture/SelfieViewModel.swift
=> Reworked Local Storage 

CHANGELOG.md, Example/Podfile.lock, SmileID.podspec, Sources/SmileID/Classes/BiometricKYC/OrchestratedBiometricKycViewModel.swift, Sources/SmileID/Classes/Networking/Models/UploadRequest.swift, Sources/SmileID/Classes/SmileID.swift
=> Update IdInfo in BiometricKYC

Example/Podfile.lock, Example/SmileID.xcodeproj/project.pbxproj, Package.swift, SmileID.podspec
Story: https://app.shortcut.com/smileid/story/12123
Adds Lottie
=> Add Lottie

Sources/SmileID/Classes/BiometricKYC/OrchestratedBiometricKycScreen.swift, Sources/SmileID/Classes/BiometricKYC/OrchestratedBiometricKycViewModel.swift, Sources/SmileID/Classes/DocumentVerification/Model/OrchestratedDocumentVerificationViewModel.swift, Sources/SmileID/Classes/DocumentVerification/View/OrchestratedDocumentVerificationScreen.swift, Sources/SmileID/Classes/Helpers/LocalStorage.swift, Sources/SmileID/Classes/SelfieCapture/SelfieViewModel.swift, Sources/SmileID/Classes/SelfieCapture/View/OrchestratedSelfieCaptureScreen.swift, Sources/SmileID/Resources/Localization/en.lproj/Localizable.strings
Update Offline Message in Orchestrated Screens in Offline State to show accurate message and set the status to true if the job is pending submission at a later point when the internet connection is back
=> Update Offline Message in Orchestrated Screens in Offline State

CHANGELOG.md, Example/Podfile.lock, SmileID.podspec, Sources/SmileID/Classes/Networking/Models/MultipartBody.swift, Sources/SmileID/Classes/SmileID.swift
We need to make this public, so we can create the struct from Flutter/RN SDKs
=> Made MultipartBody initializer public

Sources/SmileID/Classes/Networking/RestServiceClient.swift, Sources/SmileID/Classes/Networking/ServiceRunnable.swift, Sources/SmileID/Classes/Networking/SmileIDService.swift, Sources/SmileID/Classes/Networking/URLSession/URLSessionRestServiceClient.swift, Sources/SmileID/Classes/Views/JobSubmittable.swift, Tests/Mocks/NetworkingMocks.swift
Story: https://app.shortcut.com/smileid/story/12926/
Convert functions on networking interfaces from AnyPublisher to async throwing functions.
The project currently doesn't build successfully with this PR but more PRs will follow.,
N/A
N/A
=> Convert Networking Interface Functions to Async Throwing

CHANGELOG.md, Sources/SmileID/Classes/BiometricKYC/OrchestratedBiometricKycScreen.swift, Sources/SmileID/Classes/BiometricKYC/OrchestratedBiometricKycViewModel.swift, Sources/SmileID/Classes/DocumentVerification/Model/OrchestratedDocumentVerificationViewModel.swift, Sources/SmileID/Classes/DocumentVerification/View/OrchestratedDocumentVerificationScreen.swift, Sources/SmileID/Classes/SelfieCapture/SelfieViewModel.swift, Sources/SmileID/Classes/SelfieCapture/View/OrchestratedSelfieCaptureScreen.swift, Sources/SmileID/Classes/Util.swift, Sources/SmileID/Resources/Localization/en.lproj/Localizable.strings
Story: https://app.shortcut.com/smileid/story/12097/update-generic-errors-with-actual-platform-errors-in-mobile-sdks-v10
This ticket changes the default error we show, and replace that with the actual platform code that we get from the api. We allow localization by allowing partners to overide the default empty strings defined on the sdk with the specific messages they would like to show their users
changes to the development environment (if applicable) and all …
=> Update Generic SDK Errors with Platform Errors

Example/SmileID/BiometricKYC/BiometricKycWithIdInputScreenViewModel.swift, Example/SmileID/DocumentSelectorViewModel.swift, Example/SmileID/DocumentVerificationIdTypeSelector.swift, Example/SmileID/EnhancedKYC/EnhancedKycWithIdInputScreenViewModel.swift, Sources/SmileID/Classes/BiometricKYC/OrchestratedBiometricKycViewModel.swift, Sources/SmileID/Classes/DocumentVerification/Model/OrchestratedDocumentVerificationViewModel.swift, Sources/SmileID/Classes/Networking/RestServiceClient.swift, Sources/SmileID/Classes/Networking/ServiceRunnable.swift, Sources/SmileID/Classes/Networking/SmileIDService.swift, Sources/SmileID/Classes/Networking/URLSession/URLSessionPublisher.swift, Sources/SmileID/Classes/Networking/URLSession/URLSessionRestServiceClient.swift, Sources/SmileID/Classes/SelfieCapture/SelfieViewModel.swift, Sources/SmileID/Classes/SmileID.swift, Sources/SmileID/Classes/Views/JobSubmittable.swift, Tests/Mocks/NetworkingMocks.swift, Tests/Networking/PollingTests.swift, Tests/Networking/URLSessionRestServiceClientTests.swift
Story: https://app.shortcut.com/smileid/story/12926/
* Update the core networking implementation and mock implementation to use the new async functions
* Update unit tests to use the new async functions as well. 
~This PR was intended to fix all the compiler errors so that the project could build successfully. The project has not been properly tested end-to-end after the refactoring work. Subsequent PRs will address any issues encountered during end-to-end and usability testing.
⛔️ 7 Tests failing so far~
Tests are now passing after pushing fixes to failing tests.
N/A
N/A
=> Update Core Networking Implementation

CHANGELOG.md, Example/Podfile.lock, Example/SmileID/BiometricKYC/BiometricKycWithIdInputScreenViewModel.swift, Example/SmileID/DocumentSelectorViewModel.swift, Example/SmileID/DocumentVerificationIdTypeSelector.swift, Example/SmileID/EnhancedKYC/EnhancedKycWithIdInputScreenViewModel.swift, SmileID.podspec, Sources/SmileID/Classes/BiometricKYC/OrchestratedBiometricKycViewModel.swift, Sources/SmileID/Classes/DocumentVerification/Model/OrchestratedDocumentVerificationViewModel.swift, Sources/SmileID/Classes/Networking/APIError.swift, Sources/SmileID/Classes/Networking/RestServiceClient.swift, Sources/SmileID/Classes/Networking/ServiceRunnable.swift, Sources/SmileID/Classes/Networking/SmileIDService.swift, Sources/SmileID/Classes/Networking/URLSession/URLSessionPublisher.swift, Sources/SmileID/Classes/Networking/URLSession/URLSessionRestServiceClient.swift, Sources/SmileID/Classes/SelfieCapture/SelfieViewModel.swift, Sources/SmileID/Classes/SmileID.swift, Sources/SmileID/Classes/Views/JobSubmittable.swift, Tests/Mocks/NetworkingMocks.swift, Tests/Networking/EnhancedKycTest.swift, Tests/Networking/PollingTests.swift, Tests/Networking/URLSessionRestServiceClientTests.swift
Story: https://app.shortcut.com/smileid/story/12926
This includes the following changes:
* Migrate networking interface functions to from AnyPublisher to async functions
* Update core implementation of the interfaces to use the new async functions
* Update Mock implementations of the interfaces and the related unit tests.
N/A
Pull and run this branch and test that all functionalities still work in the SDK and Demo app.
N/A
=> Convert AnyPublisher to async/await

Example/SmileID/HomeView.swift, Example/SmileID/HomeViewController.swift, Example/SmileID/HomeViewModel.swift, Sources/SmileID/Classes/BiometricKYC/OrchestratedBiometricKycViewModel.swift, Sources/SmileID/Classes/DocumentVerification/Model/DocumentCaptureViewModel.swift, Sources/SmileID/Classes/DocumentVerification/Model/OrchestratedDocumentVerificationViewModel.swift, Sources/SmileID/Classes/DocumentVerification/View/DocumentCaptureScreen.swift, Sources/SmileID/Classes/DocumentVerification/View/OrchestratedDocumentVerificationScreen.swift, Sources/SmileID/Classes/Networking/Models/v2/Metadata.swift, Sources/SmileID/Classes/SelfieCapture/SelfieViewModel.swift, Sources/SmileID/Classes/SelfieCapture/SmartSelfieResultDelegate.swift, Tests/Mocks/NetworkingMocks.swift
Story: https://app.shortcut.com/smileid/story/13073/collect-metadata-on-mobile-sdk-v10-ios
Added tracking for Selfie Capture Mode, Document Auto Capture and Retries Count
=> Selfie Capture Mode, Document Auto Capture and Retries Count

Example/SmileID.xcodeproj/project.pbxproj, Example/SmileID/Home/HomeViewModel.swift, Example/SmileID/Jobs/JobItemModel.swift, Example/SmileID/Jobs/JobListItem.swift, Example/SmileID/Jobs/JobsView.swift, Example/SmileID/Jobs/JobsViewModel.swift, Example/SmileID/Models/DataStoreClient.swift, Example/SmileID/Models/Job.swift
Story: https://app.shortcut.com/smileid/story/12793/
* Handle data store errors and show a toast where necessary.
* Update status of jobs in the list with polling API.
N/A
N/A.
N/A
=> Task Update Jobs Status

CHANGELOG.md, Example/Podfile.lock, SmileID.podspec, Sources/SmileID/Classes/SmileID.swift
=> Release 10.2.3

Sources/SmileID/Classes/Networking/Models/ValidDocuments.swift
=> Fix mulitple document types

CHANGELOG.md, Sources/SmileID/Classes/BiometricKYC/OrchestratedBiometricKycViewModel.swift, Sources/SmileID/Classes/DocumentVerification/Model/OrchestratedDocumentVerificationViewModel.swift
Story: https://app.shortcut.com/smileid/story/13310/fix-retry-true-flag-on-normal-flow-on-the-sdk
=> Set retry flag true on Prep Upload

CHANGELOG.md
=> feat: correct changelog

Sources/SmileID/Classes/Consent/OrchestratedConsentScreen.swift, Sources/SmileID/Classes/DocumentVerification/View/CaptureButton.swift, Sources/SmileID/Classes/DocumentVerification/View/DocumentCaptureInstructionsScreen.swift, Sources/SmileID/Classes/DocumentVerification/View/DocumentCaptureScreen.swift, Sources/SmileID/Classes/DocumentVerification/View/DocumentShapedBoundingBox.swift, Sources/SmileID/Classes/Navigation/NavigationBar.swift, Sources/SmileID/Classes/SelfieCapture/View/FaceShapedProgressIndicator.swift, Sources/SmileID/Classes/SelfieCapture/View/InfiniteProgressBar.swift, Sources/SmileID/Classes/SelfieCapture/View/SelfieCaptureScreen.swift, Sources/SmileID/Classes/SelfieCapture/View/SmartSelfieInstructionsScreen.swift, Sources/SmileID/Classes/SelfieCapture/View/SmileButton.swift, Sources/SmileID/Classes/Views/ImageCaptureConfirmationDialog.swift, Sources/SmileID/Classes/Views/ProcessingScreen.swift, Sources/SmileID/Classes/Views/RadioGroupSelector.swift, Sources/SmileID/Classes/Views/SearchableDropdownSelector.swift
=> Temporarily force the light mode even if the user is in dark mode

Example/SmileID.xcodeproj/project.pbxproj, Example/Tests/FaceValidatorTests.swift
Story: https://app.shortcut.com/smileid/story/13080/
Add these test cases for FaceValidator class.
* Valid face
* Face too small
* Face too large
* Face off centre
* Poor brightness
* Poor selfie quality 
* User instructions for liveness task
N/A.
N/A.
N/A.
=> Face Validator Tests

Package.resolved, Package.swift
* Fix wrong version number set for FingerprintJS package and dependency name causing spm not to resolve
N/A.
N/A.
N/A.
=> Fix SPM Dependency Issue

CHANGELOG.md, Sources/SmileID/Classes/DocumentVerification/Model/OrchestratedDocumentVerificationViewModel.swift
=> Fixed Missing Document Type

CHANGELOG.md
* update changelog for release 10.3.5
N/A.
N/A.
N/A.
=> chore: release v10.3.5

Example-Objc/Example-Objc.xcodeproj/project.pbxproj, Example-Objc/Example-Objc.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Example-Objc/Example-Objc/AppDelegate.h, Example-Objc/Example-Objc/AppDelegate.m, Example-Objc/Example-Objc/Assets.xcassets/AccentColor.colorset/Contents.json, Example-Objc/Example-Objc/Assets.xcassets/AppIcon.appiconset/Contents.json, Example-Objc/Example-Objc/Assets.xcassets/Contents.json, Example-Objc/Example-Objc/Base.lproj/LaunchScreen.storyboard, Example-Objc/Example-Objc/Base.lproj/Main.storyboard, Example-Objc/Example-Objc/Info.plist, Example-Objc/Example-Objc/SceneDelegate.h, Example-Objc/Example-Objc/SceneDelegate.m, Example-Objc/Example-Objc/SmileID/EnhancedSelfieCaptureViewController.swift, Example-Objc/Example-Objc/SmileID/Example-Objc-Bridging-Header.h, Example-Objc/Example-Objc/SmileID/SmartSelfieCaptureViewController.swift, Example-Objc/Example-Objc/SmileID/SmileIDManager.h, Example-Objc/Example-Objc/SmileID/SmileIDManager.m, Example-Objc/Example-Objc/ViewController.h, Example-Objc/Example-Objc/ViewController.m, Example-Objc/Example-Objc/main.m, Example-Objc/README.md, Example/SmileID.xcworkspace/xcshareddata/swiftpm/Package.resolved
Story: https://app.shortcut.com/smileid/story/14974/
* Add a new Xcode project based on Objective-C and UIKit to demonstrate how to use SmileID iOS SDK in an Objective-C project.
N/A.
N/A.
N/A.
=> Objective-C Sample Project

Sources/SmileID/Classes/SmileID.swift
* version number update that was missing for the last release.
N/A.
N/A.
N/A
=> bump smileid version

Example/SmileID.xcodeproj/project.pbxproj, Example/SmileID/BiometricKYC/BiometricKycWithIdInputScreen.swift
* prep work for the recent released demo app.
* make biometric use classic selfie capture by default.
N/A.
N/A.
N/A
=> Demo release 1.5.0

Sources/SmileID/Classes/Metadata/MetadataKey.swift, Sources/SmileID/Classes/Metadata/MetadataModels.swift, Sources/SmileID/Classes/Metadata/NetworkMetadataProvider.swift, Sources/SmileID/Classes/Networking/Models/EnhancedKyc.swift, Sources/SmileID/Classes/SmileID.swift
Story: https://app.shortcut.com/smileid/story/15152/
* Introduce a new method for wrapper SDKs to collect sdk name and version metadata.
N/A
N/A
N/A
=> Metadata: Wrapper Name & Version
