- Sources/SmileID/Classes/Helpers/LocalizedStringExtensions.swift
- Sources/SmileID/Classes/Helpers/SmileIDLocalizableStrings.swift
- Sources/SmileID/Classes/Helpers/SmileIDResourcesHelper.swift
- Sources/SmileID/Classes/SmileID.swift
Enables partners supply their own Localizable strings file. This enables them customise all the strings within the SDK.
The screenshot below shows the SDK supporting an RTL locale
> Support overriding localized strings

- CHANGELOG.md
- Sources/SmileID/Classes/Networking/Models/PrepUpload.swift
Removes the `file_name` from prep upload, as it is no longer required
> Remove `filename` property from `PrepUploadRequest`

- CHANGELOG.md
- Example/SmileID.xcodeproj/project.pbxproj
- Example/SmileID.xcodeproj/xcshareddata/xcschemes/SmileID-Example.xcscheme
- Example/SmileID/HomeViewModel.swift
- Sources/SmileID/Classes/Networking/Models/BVN.swift
- Sources/SmileID/Classes/Networking/Models/JobType.swift
- Sources/SmileID/Classes/Networking/SmileIDService.swift
- Tests/Mocks/NetworkingMocks.swift
Story: https://app.shortcut.com/smileid/story/9097/add-bvn-enforced-consent-screens-to-the-v10-sdk-ios
Starts the work for adding BVN Consent. This adds the API calls and models
> Add BVN networking models

- Example/SmileID/EnterUserIDView.swift
- Example/SmileID/HomeView.swift
- Example/SmileID/HomeViewModel.swift
- Example/SmileID/ProductCell.swift
- Example/SmileID/SmileTextField.swift
Since the SmartSelfie Enroll and Auth jobs share the same delegate and since the inital job result is still processing, we can't tell in the delegate what the job type is. This makes a change to define a separate delegate for enroll, so that we can save the userId used for enrollment and pre-populate the smartselfie auth user ID text field with it
> Save SmartSelfie Enrollment userId on job completion

- Sources/.swiftlint.yml
- Sources/SmileID/Classes/Consent/OrchestratedConsentScreen.swift
- Sources/SmileID/Classes/DocumentVerification/Model/OrchestratedDocumentVerificationViewModel.swift
- Sources/SmileID/Classes/SelfieCapture/ViewModel/SelfieCaptureViewModel.swift
- Sources/SmileID/Classes/Views/ProcessingScreen.swift
Story: https://app.shortcut.com/smileid/story/8953
Update Processing State name to be more generic, as it was originally intentioned
> Update ProcessingState naming

- CHANGELOG.md
- Example/Podfile.lock
- Example/SmileID.xcodeproj/project.pbxproj
- Sources/SmileID/Classes/DocumentVerification/View/OrchestratedDocumentVerificationScreen.swift
- Sources/SmileID/Classes/SmileID.swift
Story: N/A
added allowAgentMode on docv and enhanced docv
> Added agent mode on DocV and EnhancedDocV 

- CHANGELOG.md
- Example/Podfile.lock
- Example/SmileID.xcodeproj/project.pbxproj
- Example/SmileID/BiometricKYC/BiometricKycWithIdInputScreen.swift
- Example/SmileID/BiometricKYC/BiometricKycWithIdInputScreenViewModel.swift
- Example/SmileID/BiometricKYC/IdInfoInputScreen.swift
- Example/SmileID/BiometricKYC/IdInfoInputViewModel.swift
- Example/SmileID/HomeView.swift
- Sources/SmileID/Classes/BiometricKYC/OrchestratedBiometricKycScreen.swift
- Sources/SmileID/Classes/BiometricKYC/OrchestratedBiometricKycViewModel.swift
- Sources/SmileID/Classes/Networking/Models/Services.swift
- Sources/SmileID/Classes/Networking/NetworkUtil.swift
- Sources/SmileID/Classes/SmileID.swift
- Sources/SmileID/Resources/Localization/en.lproj/Localizable.strings
This unbundles the Consent Screen from Biometric KYC and additionally exposes the Consent Screen as its own SwiftUI view. It also moves the ID type selection and input screen from the SDK back into the app. The overall flow from the sample app's perspective should remain the exact same.
> Remove consent screen from Biometric KYC

- CHANGELOG.md
- Sources/SmileID/Classes/DocumentVerification/View/DocumentShapedBoundingBox.swift
- Sources/SmileID/Classes/Util.swift
- Sources/SmileID/Classes/Views/AspectRatioRoundedRectangle.swift
Story: https://app.shortcut.com/smileid/story/11225
This fixes a bug where the document cutout would display a white box on older iOS versions. Previously, we were using the `.destinationOut` blend mode. This change uses a different approach, leveraging `clipPath`, the `evenOdd` fill, and some stacked shapes. Inspiration is directly taken from here: http://josephvb.com/posts/cutout-shape/
This addresses only the document overlay cutout, not the face shape cutout yet.
Visit the smart selfie capture screen and take a screenshot. Notice how the face shape is simply all black. Visit the document verification capture screen and take a screenshot. Notice that we can actually see the actual screen contents.
~I don't have an iOS 14 device to test on, so at the moment, it is difficult to say …
> Fix white document overlay cutout

- Sources/SmileID/Classes/Networking/Models/Authentication.swift
- Sources/SmileID/Classes/Networking/Models/ValidDocuments.swift
Makes AuthenticationResponse encodable for use with React Native
> Make AuthenticationResponse and ProductsConfigResponse Encodable

- Sources/SmileID/Classes/SelfieCapture/View/FaceShapedProgressIndicator.swift
Draws the white overlay on the selfie screen underneath the navigation bar
> Draw camera cover under nav bar

- .github/workflows/build-app.yml
- .github/workflows/carthage-release.yml
- .github/workflows/sdk-primary.yml
Upgrades the macOS runners to macOS 14. This comes with the additional benefit of running on M1 CPU cores now (previously this was only available on `-large` runners).
Additional details [here](https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/)
> Upgrade runner to macOS 14

- CHANGELOG.md
- Sources/SmileID/Classes/DocumentVerification/View/OrchestratedDocumentVerificationScreen.swift
Story: https://app.shortcut.com/smileid/story/11625
When capturing the back of ID, don't show the skip button
> Disable Skip Button on Back ID Capture Screen

- SmileID.podspec
This PR updates smileidentity.com to usesmileid.com as part of the gradual transition to using the new domain name throughout the system.
> update smileidentity.com to usesmileid.com

- CHANGELOG.md
- Example/SmileID.xcodeproj/project.pbxproj
- Example/SmileID/PrivacyInfo.xcprivacy
- Package.swift
- SmileID.podspec
- SmileID.xcodeproj/project.pbxproj
- Sources/SmileID/Resources/PrivacyInfo.xcprivacy
Story: https://app.shortcut.com/smileid/story/12249
Adds PrivacyInfo to SDK and Sample app. 
The attributes included for the SDK are: Head movement and Environment scanning; both for App functionality reasons. No Required Reason APIs. 
The attributes included for the sample app are: User ID; for App functionality. The Sentry dependency automatically adds the Crash Reporting attribute. No Required Reason APIs
The xcframework generated by `./Scripts/build_frameworks.sh` doesn't contain the PrivacyInfo file currently
> Add PrivacyInfo

- CHANGELOG.md
- Example/Podfile.lock
- Example/SmileID.xcodeproj/project.pbxproj
- SmileID.podspec
- Sources/SmileID/Classes/BiometricKYC/OrchestratedBiometricKycViewModel.swift
- Sources/SmileID/Classes/DocumentVerification/Model/OrchestratedDocumentVerificationViewModel.swift
- Sources/SmileID/Classes/Helpers/LocalStorage.swift
- Sources/SmileID/Classes/SelfieCapture/SelfieViewModel.swift
- Sources/SmileID/Classes/SmileID.swift
Story: https://app.shortcut.com/smileid/story/12858
`handleOfflineJobFailure` now returns a boolean indicating whether files were moved. If they were, we update the file paths in the ViewModel using the result of `getFileByType` with `submitted=true`. getFileType was updated to add this new submitted parameter.
Prepares for 10.1.4 release
> Update filepaths when files move

- Example/SmileID.xcodeproj/project.pbxproj
- Example/SmileID/BiometricKYC/BiometricKycWithIdInputScreen.swift
- Example/SmileID/BiometricKYC/BiometricKycWithIdInputScreenViewModel.swift
- Example/SmileID/EnhancedKYC/EnhancedKycWithIdInputScreen.swift
- Example/SmileID/EnhancedKYC/EnhancedKycWithIdInputScreenViewModel.swift
- Example/SmileID/Helpers/Date+Extension.swift
- Example/SmileID/Helpers/Date+Extensions.swift
- Example/SmileID/Helpers/String+Extensions.swift
- Example/SmileID/Home/HomeView.swift
- Example/SmileID/Home/HomeViewModel.swift
- Example/SmileID/Jobs/JobListItem.swift
- Example/SmileID/Models/DataStoreClient.swift
- Example/SmileID/Models/DataStoreError.swift
- Example/SmileID/Models/Job.swift
- Example/SmileID/Models/JobData.swift
- Example/SmileID/Models/SmileID.xcdatamodeld/SmileID.xcdatamodel/contents
- Sources/SmileID/Classes/Networking/Models/JobStatus.swift
Story: https://app.shortcut.com/smileid/story/12793/
* Change job timestamp data type to Date for better representation.
* Inject userId and jobId into verification product flows
* Add new case to ActionResult to solve JSON decoding issue for job status API response.
N/A.
Launch the app and tap on the Jobs tab. Assuming you already have jobs saved locally, the most recent jobs should now appear at the top of the list.
N/A.
> Sort Jobs List and Fix Job Status Update Issue

- Example/SmileID.xcodeproj/project.pbxproj
- Example/SmileID/Home/HomeView.swift
- Example/SmileID/Home/HomeViewModel.swift
- Example/SmileID/Jobs/JobItemModel.swift
- Example/SmileID/Jobs/JobsView.swift
Story: https://app.shortcut.com/smileid/story/12793/
* Use newly generated userId for authentication jobs instead of smart selfie enrolment userId
* Hide clear jobs button if there are no jobs.
N/A.
N/A
N/A
> Fix Jobs User Id issue

- Example/SmileID.xcodeproj/project.pbxproj
- Example/SmileID/App/RootView.swift
- Example/SmileID/Components/IndeterminateProgressView.swift
- Example/SmileID/Home/HomeViewModel.swift
- Example/SmileID/Jobs/JobItemModel.swift
- Example/SmileID/Jobs/JobListItem.swift
- Example/SmileID/Jobs/JobsView.swift
- Example/SmileID/Jobs/JobsViewModel.swift
- Example/SmileID/Models/DataStoreClient.swift
- Example/SmileID/Models/Job.swift
- Example/SmileID/Models/JobData.swift
- Example/SmileID/Models/SmileID.xcdatamodeld/SmileID.xcdatamodel/contents
- Sources/SmileID/Classes/Networking/Models/JobStatus.swift
Story: https://app.shortcut.com/smileid/story/12793
* Introduce an indeterminate Progress View to Jobs List Item to show progress of job status request
* Add new partnerId and isProduction properties to Job models to scope the list based on partner configuration and environment.
N/A
N/A
| With Progress View | With PartnerId and Environment |
| --- | --- |
| <img src="https://github.com/smileidentity/ios/assets/8595853/f682fecb-9fd3-4b8a-9b92-9c48de4914c8" /> | <img src="https://github.com/user-attachments/assets/ff7f3a96-bf1b-47d0-8390-4e61b46e6565" /> |
> Status Progress and Scoping of Persisted Jobs

- Example/SmileID.xcodeproj/project.pbxproj
- Example/SmileID/App/RootView.swift
- Example/SmileID/App/RootViewModel.swift
- Example/SmileID/Jobs/JobListItem.swift
- Example/SmileID/Jobs/JobsView.swift
- Example/SmileID/Settings/SettingsView.swift
- Example/SmileID/Settings/SettingsViewModel.swift
* move smile config decoding and initialisation into root view model. 
* add a closure to send back update config to root view so that the entire app is refreshed.
N/A.
* Launch the app with configuration already applied.
* Go to Settings and update smile config with another partner information.
* Go to Home Screen to see that the partner information has been updated
* If you have jobs saved locally, the Jobs list screen should also reflect the change.
N/A
> Refresh Entire App when Smile Config is Updated

- CHANGELOG.md
- Example/Podfile.lock
- Sources/SmileID/Classes/Networking/Models/PrepUpload.swift
- Sources/SmileID/Classes/SmileID.swift
Story: https://app.shortcut.com/smileid/story/13152
The link returned by Prep Upload has an expiration. However, the job is still considered created at the time the link expires. So, if the user encounters a scenario where prep upload succeeds but upload fails, and the partner app's implementation tries again using `SmileID.submitJob`, it currently fails with error code 2215. 
With this change, we check for this error code explicitly and set the retry flag to true so that we can obtain a new upload URL
Related: https://github.com/smileidentity/android/pull/411
> Set retry flag on error code 2215

- CHANGELOG.md
- Example/SmileID/Components/SmileEnvironmentToggleButton.swift
- Example/SmileID/Home/HomeViewController.swift
- Sources/SmileID/Classes/SmileID.swift
> API Keys Fix per Environment

- CHANGELOG.md
- Example/Podfile.lock
- Example/SmileID.xcodeproj/project.pbxproj
- Package.resolved
- Package.swift
- SmileID.podspec
- SmileID.xcodeproj/project.pbxproj
- SmileID.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Sources/SmileID/Classes/BiometricKYC/OrchestratedBiometricKycViewModel.swift
- Sources/SmileID/Classes/DocumentVerification/Model/OrchestratedDocumentVerificationViewModel.swift
- Sources/SmileID/Classes/Helpers/LocalStorage.swift
- Sources/SmileID/Classes/SmileID.swift
Story: https://app.shortcut.com/smileid/story/12554/ios-integrate-with-new-zip-library
Swap zip library implementation on iOS to zip in memory
> Swap zip library implementation on iOS to zip in memory

- CHANGELOG.md
- Example/Podfile.lock
- SmileID.podspec
- Sources/SmileID/Classes/SmileID.swift
> Prepare 10.2.7 release

- CHANGELOG.md
- Sources/SmileID/Classes/BiometricKYC/OrchestratedBiometricKycViewModel.swift
- Sources/SmileID/Classes/DocumentVerification/Model/OrchestratedDocumentVerificationViewModel.swift
- Sources/SmileID/Classes/Networking/APIError.swift
- Sources/SmileID/Classes/Networking/RestServiceClient.swift
- Sources/SmileID/Classes/Networking/ServiceRunnable.swift
- Sources/SmileID/Classes/Networking/SmileIDService.swift
- Sources/SmileID/Classes/Networking/URLSession/URLSessionRestServiceClient.swift
- Sources/SmileID/Classes/SmileID.swift
- Sources/SmileID/Classes/Util.swift
- Sources/SmileID/Classes/Views/JobSubmittable.swift
- Tests/Mocks/NetworkingMocks.swift
Story: https://app.shortcut.com/smileid/story/13466/
* Add a new argument for SmileID initialiser to specify timeout for upload requests.
* Refactor upload method to use async await instead of AsyncThrowingStream.
* Handle URLError and show localizedDescription to users.
Confirm that timeout errors are handled.
* In HomeViewModel add a short `uploadRequestTimeout` argument to the SmileID initialiser like 1sec.
* Run a job that involves upload requests
* The job should time out.
https://portal.usesmileid.com/admin/job/production/172668761
> Add Upload Request Timeout, Fix API Error Messages

- Example/SmileID/Home/HomeView.swift
- Example/SmileID/Home/HomeViewModel.swift
Story: https://app.shortcut.com/smileid/story/12173/
This change is a potential fix for a lot of state management issues in the Example app and it should minimise the number of times the HomeViewModel is reinitialised restricting view re-render to just when certain properties within the scope change rather than refreshing the entire application when any property changes.
* Replace `ObservedObject` with `StateObject`. 
* Get rid of unused `networkMonitor` variable in `HomeViewModel`
N/A.
N/A.
N/A
> Potential Fix for Freezing Image Analysis

- CHANGELOG.md
- Sources/SmileID/Classes/BiometricKYC/OrchestratedBiometricKycScreen.swift
- Sources/SmileID/Classes/BiometricKYC/OrchestratedBiometricKycViewModel.swift
- Sources/SmileID/Classes/DocumentVerification/Model/OrchestratedDocumentVerificationViewModel.swift
- Sources/SmileID/Classes/Helpers/LocalStorage.swift
- Sources/SmileID/Classes/Networking/APIError.swift
- Sources/SmileID/Classes/Networking/SmileIDService.swift
- Sources/SmileID/Classes/SelfieCapture/SelfieViewModel.swift
- Sources/SmileID/Classes/SelfieCapture/View/OrchestratedSelfieCaptureScreen.swift
Story: https://app.shortcut.com/smileid/story/13656/
* Refactor submission for BiometricKYC Jobs
* Fix how offline job failure scenario is handled.
N/A.
The bug here is the unresponsiveness of the retry action when trying to submit a biometric job that initially failed due to internet connection:
So when you start a biometric KYC job, before submitting, you turn off your internet
Then you get a failed pop up for failure due to internet connection
Then you turn on internet back on and click retry
If everything goes well the job should be submitted
N/A
> Fix Retry After Previous Offline State.

- CHANGELOG.md
- Example/Podfile.lock
- SmileID.podspec
- Sources/SmileID/Classes/SmileID.swift
Prepare for release - 10.2.14
N/A.
N/A.
N/A.
> chore: bump version to 10.2.15

- Example/SmileID.xcodeproj/project.pbxproj
- Example/SmileID/BiometricKYC/BiometricKycWithIdInputScreen.swift
- Example/SmileID/EnhancedKYC/EnhancedKycWithIdInputScreen.swift
- Example/SmileID/Home/HomeView.swift
- Example/SmileID/Home/HomeViewModel.swift
- Example/SmileID/Home/ProductCell.swift
- Example/SmileID/Info.plist
- Sources/SmileID/Classes/Consent/OrchestratedConsentScreen.swift
- Sources/SmileID/Classes/SelfieCapture/EnhancedSmartSelfieViewModel.swift
- Sources/SmileID/Classes/SelfieCapture/SelfieSubmissionManager.swift
- Sources/SmileID/Classes/SelfieCapture/View/OrchestratedSelfieCaptureScreen.swift
- Sources/SmileID/Classes/SelfieCapture/View/SelfieCaptureScreen.swift
- Sources/SmileID/Classes/SmileID.swift
- Sources/SmileID/Classes/Views/SearchableDropdownSelector.swift
* Grab last selfie enrollment user id from the paste board for use during smart selfie authentication
* Fix layout issue with Biometric KYC during country and ID type selection.
* Resolve ForEach data identifiable requirement warning.
* Some code formatting.
* Replace ObservableObject with StateObject in views where view model isn't injected.
* Fix isEnroll flag with orchestrated enhance smart selfie capture.
* Fix typos in localized instructions copy.
* Consent screen views might be compressed on small screen devices.
* Try to run selfie enrollment multiple times and you should be able to submit the job successfully without user already enrolled API error.
* Try running Biometric KYC job and you should be able to select a country and ID …
> Fix UserID Refresh for New Jobs

- Example/SmileID/Home/HomeView.swift
- Sources/SmileID/Classes/SelfieCapture/EnhancedSmartSelfieViewModel.swift
- Sources/SmileID/Classes/SelfieCapture/SelfieSubmissionManager.swift
- Sources/SmileID/Classes/SelfieCapture/View/OrchestratedEnhancedSelfieCaptureScreen.swift
- Sources/SmileID/Classes/SmileID.swift
> SmileID Enhanced Views

- Example/Podfile.lock
- SmileID.podspec
- Sources/SmileID/Classes/SmileID.swift
> Release 10.3.1

- CHANGELOG.md
- Example/Podfile.lock
- Example/SmileID/Home/HomeViewModel.swift
- SmileID.podspec
- Sources/SmileID/Classes/Networking/APIError.swift
- Sources/SmileID/Classes/SelfieCapture/EnhancedSmartSelfieViewModel.swift
- Sources/SmileID/Classes/SelfieCapture/View/EnhancedSelfieCaptureScreen.swift
- Sources/SmileID/Classes/SelfieCapture/View/SelfieCaptureScreen.swift
- Sources/SmileID/Classes/SmileID.swift
* Expose the initialisers of Selfie capture screen and Enhanced Selfie capture screen publicly so that Flutter can have access to it.
N/A.
N/A.
N/A
> Fix Flutter Issues

- Sources/SmileID/Classes/SelfieCapture/EnhancedSmartSelfieViewModel.swift
- Sources/SmileID/Classes/SelfieCapture/SelfieSubmissionManager.swift
* move operation canceled callback inside the cancel action
* So that the cancel action is properly called when there is an error submitting selfie.
N/A.
N/A.
N/A
> Fix Cancel Action on Error

- CHANGELOG.md
- Example/Podfile.lock
- SmileID.podspec
- Sources/SmileID/Classes/SmileID.swift
Prepare SDK for release - v10.3.3
> chore: release v10.3.3

- Example/SmileID/Home/HomeView.swift
* Change StateObject to ObservedObject so that injected config can re-render the view.
N/A.
* Launch the Demo app and switch to the Settings.
* Tap on "Update Smile Config"
* Provide partner config with a string or QR code
* Switch back to Home Tab to see the current partner config info.
* You should see the update without having to relaunch the app.
* Please also test the jobs to be sure that this change doesn't break anything on your device. (Jobs are working fine on mine).
> Update Partner Config without Relaunching Demo App

- CHANGELOG.md
- Sources/SmileID/Classes/Networking/ServiceRunnable.swift
* Add default headers of partner id, source sdk and source sdk version to all GET and POST requests. (Multipart requests already had this).
N/A.
* Run any job successfully.
* Shake your device to bring up networking logger
* Confirm that the default headers were part of the request.
N/A
> Auth Smile Headers

- CHANGELOG.md
- Example/Podfile.lock
- SmileID.podspec
- Sources/SmileID/Classes/DocumentVerification/Model/OrchestratedDocumentVerificationViewModel.swift
- Sources/SmileID/Classes/SmileID.swift
- Sources/SmileID/Resources/Localization/en.lproj/Localizable.strings
Story: https://app.shortcut.com/smileid/story/14901/
* The back image for document was required for the success method of document verification result delegate but it shouldn't be because there is a flag `captureBothSides` that allows only front of a document to be captured. Made this not required
N/A.
- When initiating document verification orchestrated flow in the SDK pass a false value to the `captureBothSides` flag
- Run a document verification job and tap continue button after selfie capture. 
- The flow should be dismissed without an unknown error.
N/A
> Fix Required Document Back Image Issue

- Example/SmileID.xcodeproj/project.pbxproj
- Example/SmileID/Home/HomeView.swift
* Fix user id and job id not refreshing on demo app
* bump build number
N/A.
N/A.
N/A
> Fix UserID and JobID Not Refreshing

- CHANGELOG.md
- Example/SmileID/DocumentVerification/EnhancedDocumentVerificationWithSelector.swift
- Sources/SmileID/Classes/DocumentVerification/Model/OrchestratedDocumentVerificationViewModel.swift
- Sources/SmileID/Classes/DocumentVerification/View/OrchestratedDocumentVerificationScreen.swift
- Sources/SmileID/Classes/SmileID.swift
Story: https://app.shortcut.com/smileid/story/14976/add-consent-screen-support-to-enhanced-doc-v-on-all-sdks
> Add Consent Information to EnhancedDocV 📸 

- Sources/SmileID/Classes/BiometricKYC/OrchestratedBiometricKycScreen.swift
- Sources/SmileID/Classes/DocumentVerification/View/OrchestratedDocumentVerificationScreen.swift
* use stateobject for orchestrated biometric and docv to avoid multiple instances at a time and improve memory.
N/A.
Test all Document Verification and Biometric KYC and all jobs should be submit successfully.
N/A.
> Use StateObject for SDK Views

- CHANGELOG.md
- Example/Podfile.lock
- SmileID.podspec
- Sources/SmileID/Classes/SmileID.swift
Story: https://app.shortcut.com/smileid/story/15242/enable-support-for-standalone-enhanced-smartselfie-for-all-sdks
Skip Api submission functionality for selfie capture screens without enrollment
N/A
* Run SmartSelfie™ enrollment capture flow without skipApiSubmission, job should be submitted
* Run SmartSelfie™ enrollment capture flow skipApiSubmission true , job should NOT be submitted
* Run Enhanced SmartSelfie™ enrollment capture flow without skipApiSubmission, job should be submitted
* Run Enhanced  SmartSelfie™ enrollment capture flow skipApiSubmission true , job should NOT be submitted
N/A
> feat:skip api submission
